---
openapi: 3.0.3
x-zally-ignore: [101, 104, 105]
info:
  contact:
    email: support@vwt.digital
    name: Digital Ambition Team
    url: https://vwt-digital.github.io/
  description: Endpoint to export car trips
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  title: HR Car Usage export API
  version: 1.0.0
  x-audience: company-internal
  x-api-id: ced90f23-2e25-47f0-83f1-730638beb362
servers:
  - url: /
paths:
  /exports/trips:
    get:
      description: Returns an export with a list of all car trips
      operationId: export_trips
      parameters:
        - $ref: '#/components/parameters/filterEndedAfterParam'
        - $ref: '#/components/parameters/filterEndedBeforeParam'
      responses:
        "200":
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                $ref: '#/components/schemas/TripsResponseFile'
          description: Returns a list of car trips
        "204":
          description: No Content
        "400":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        "403":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
      x-openapi-router-controller: openapi_server.controllers.default_controller
      security:
        - oauth2: [carusage.read]
  /checks/open-trips:
    get:
      description: Returns a list of all car trips that have not been exported yet
      operationId: check_open_trips
      parameters:
        - $ref: '#/components/parameters/filterEndedAfterParam'
        - $ref: '#/components/parameters/filterEndedBeforeParam'
      responses:
        "200":
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                $ref: '#/components/schemas/TripsResponseFile'
          description: Returns a list of car trips
        "204":
          description: There are no open trips under
        "400":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Bad Request
        "401":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: No authorization token provided
        "403":
          content:
            application/problem+json:
              schema:
                $ref: 'https://opensource.zalando.com/problem/schema.yaml#/Problem'
          description: Provided token doesn't have the required scope
      x-openapi-router-controller: openapi_server.controllers.default_controller
      security:
        - oauth2: [carusage.write]
components:
  parameters:
    filterEndedAfterParam:
      in: query
      name: ended_after
      required: true
      schema:
        type: string
        format: date-time
      description: Filter for trips that ended after a specific date
    filterEndedBeforeParam:
      in: query
      required: true
      name: ended_before
      schema:
        type: string
        format: date-time
      description: Filter for trips that ended before a specific date
  schemas:
    TripsResponseFile:
      example:
        results:
          - kenteken: AB123C
            begon_op: 2020-01-01T12:00:00Z
            eindigde_op: 2020-01-01T13:00:00Z
            voornaam: A
            acternaam: Niem
            afdeling_naam: test
            afdeling_nummer: 123456
            rit_soort: werk
            rit_beschrijving: Driver drove to a supermarket
      items:
        properties:
          kenteken:
            maxLength: 100
            type: string
          begon_op:
            maxLength: 100
            type: string
            format: date-time
          eindigde_op:
            maxLength: 100
            type: string
            format: date-time
          voornaam:
            maxLength: 100
            type: string
          acternaam:
            maxLength: 100
            type: string
          afdeling_naam:
            maxLength: 100
            type: string
          afdeling_nummer:
            type: integer
            format: int32
            minimum: 0
          rit_soort:
            default: werk
            enum:
              - werk
              - privé
            type: string
          rit_beschrijving:
            maxLength: 100
            type: string
        type: object
      type: array
  securitySchemes:
    oauth2:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        implicit:
          authorizationUrl: https://azuread.url/2.0/authorize
          scopes:
            carusage.read: View access to Dynamic Data Manipulation API
            carusage.write: Write access to Dynamic Data Manipulation API
      x-tokenInfoFunc: openapi_server.controllers.security_controller_.info_from_oAuth2
      x-scopeValidateFunc: connexion.decorators.security.validate_scope
